title: Mayach
email: office@mayach.in
description: "Mayach â€” Legal practice & thought leadership."
baseurl: "" 
url: "https://mayach.in"
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
collections:
  posts:
    output: true
permalink: /:categories/:year/:month/:day/:title/
